"""Comment status

Revision ID: 77db36db96ac
Revises: a5c716be2f30
Create Date: 2021-02-21 12:15:05.290064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77db36db96ac'
down_revision = 'a5c716be2f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('active', sa.Boolean(), nullable=False, default=True)) # 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'active')
    # ### end Alembic commands ###
